 version: 2.1
 orbs:
  codecov: codecov/codecov@1.0.1
 jobs:
   build:
     docker:
       - image: cimg/node:20.9.0
     steps:
       - checkout
       - run: npm i && npm test && ./node_modules/.bin/codecov
